<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_page-ville',
		'title' => 'Page ville',
		'fields' => array (
			array (
				'key' => 'field_33157182e6hj18',
				'label' => 'Garder cette page synchronisée automatiquement au wiki ?',
				'name' => 'keep_sync',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5736069ccbb62',
				'label' => 'Site web officiel',
				'name' => 'city_official_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5736696cb5ee9',
				'label' => 'Lieu et heure de rassemblement',
				'name' => 'city_gathering_details',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_3315qs318218',
				'label' => 'Page Facebook officielle',
				'name' => 'facebook_page_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_331qsd1d8218',
				'label' => 'Page Twitter officielle',
				'name' => 'twitter_page_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_331qdqd456456456452348',
				'label' => 'Rocket.Chat',
				'name' => 'chat_page_url',
				'type' => 'text',
				'default_value' => 'http://chat.nuitdebout.fr',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_3314574576sdf45658',
				'label' => 'Page Wiki',
				'name' => 'wiki_page_url',
				'type' => 'text',
				'default_value' => 'http://wiki.nuitdebout.fr',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5736075ea71fd',
				'label' => 'Position géographique',
				'name' => 'city_coordinates',
				'type' => 'google_map',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array (
				'key' => 'field_57360fe247c7b',
				'label' => 'Emails de contact',
				'name' => 'city_contact_emails',
				'type' => 'textarea',
				'instructions' => 'Mettez un email par ligne',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_57364c9f221c5',
				'label' => 'Liens externes',
				'name' => 'city_external_links',
				'type' => 'textarea',
				'instructions' => 'Un lien par ligne',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'none',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-ville.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_page-periscoper',
		'title' => 'Page Periscoper',
		'fields' => array (
			array (
				'key' => 'field_57409a3bcea70',
				'label' => 'Nom',
				'name' => 'periscoper_name',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57409a48cea71',
				'label' => 'Nom d\'utilisateur',
				'name' => 'periscoper_username',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57409f76ef236',
				'label' => 'Ville',
				'name' => 'periscoper_city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57409a54cea72',
				'label' => 'Image de profil',
				'name' => 'periscoper_profile_image',
				'type' => 'image',
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_57409a6dcea73',
				'label' => 'Interview de La Gazette',
				'name' => 'periscoper_interview_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-periscoper.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_modules',
		'title' => 'Modules',
		'fields' => array (
			array (
				'key' => 'field_5712ssd397bda1ca',
				'label' => 'Réseaux',
				'name' => '',
				'type' => 'tab',
			),
			array (
				'key' => 'field_57123987da1cb',
				'label' => 'Inclure le module réseaux sociaux',
				'name' => 'global_module_social',
				'type' => 'select',
				'choices' => array (
					'oui' => 'Oui',
					'non' => 'Non',
				),
				'default_value' => '',
				'allow_null' => 0,
				'multiple' => 0,
			),
			array (
				'key' => 'field_57123a35b63f8',
				'label' => 'Facebook',
				'name' => 'social_facebook',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'https://www.facebook.com/NuitDebout/',
				'placeholder' => 'https://facebook.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123a5db63f9',
				'label' => 'Twitter',
				'name' => 'social_twitter',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'https://twitter.com/nuitdebout',
				'placeholder' => 'https://twitter.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123a7cb63fa',
				'label' => 'Periscope',
				'name' => 'social_periscope',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'https://www.periscope.tv/RemyBuisine',
				'placeholder' => 'https://periscope.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123aa7b63fb',
				'label' => 'Instagram',
				'name' => 'social_instagram',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://instagram.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123ac0b63fc',
				'label' => 'Github',
				'name' => 'social_github',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://github.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123ad7b63fd',
				'label' => 'Youtube',
				'name' => 'social_youtube',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://youtube.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57dsdfsdfsdf63fd',
				'label' => 'Reddit',
				'name' => 'social_reddit',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://www.reddit.com/r/nuitdebout/',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123ae5b63fe',
				'label' => 'Bambuser',
				'name' => 'social_bambuser',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://bambuser.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123af6b63ff',
				'label' => 'Scoopit',
				'name' => 'social_scoopit',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://scoopit.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123b0ab6400',
				'label' => 'Tumblr',
				'name' => 'social_tumblr',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://tumblr.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57123b1db6401',
				'label' => 'Snapchat',
				'name' => 'social_snapchat',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_57123987da1cb',
							'operator' => '==',
							'value' => 'oui',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'https://snapchat.com/xxxx',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
