<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_page-ville',
		'title' => 'Page ville',
		'fields' => array (
			array (
				'key' => 'field_33157182e6hj18',
				'label' => 'Garder cette page synchronisée automatiquement au wiki ?',
				'name' => 'keep_sync',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5736069ccbb62',
				'label' => 'Site web officiel',
				'name' => 'city_official_website',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5736696cb5ee9',
				'label' => 'Lieu et heure de rassemblement',
				'name' => 'city_gathering_details',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'br',
			),
			array (
				'key' => 'field_3315qs318218',
				'label' => 'Page Facebook officielle',
				'name' => 'facebook_page_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_331qsd1d8218',
				'label' => 'Page Twitter officielle',
				'name' => 'twitter_page_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_331qdqd456456456452348',
				'label' => 'Rocket.Chat',
				'name' => 'chat_page_url',
				'type' => 'text',
				'default_value' => 'http://chat.nuitdebout.fr',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_3314574576sdf45658',
				'label' => 'Page Wiki',
				'name' => 'wiki_page_url',
				'type' => 'text',
				'default_value' => 'http://wiki.nuitdebout.fr',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5736075ea71fd',
				'label' => 'Position géographique',
				'name' => 'city_coordinates',
				'type' => 'google_map',
				'center_lat' => '',
				'center_lng' => '',
				'zoom' => '',
				'height' => '',
			),
			array (
				'key' => 'field_57360fe247c7b',
				'label' => 'Emails de contact',
				'name' => 'city_contact_emails',
				'type' => 'textarea',
				'instructions' => 'Mettez un email par ligne',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_57364c9f221c5',
				'label' => 'Liens externes',
				'name' => 'city_external_links',
				'type' => 'textarea',
				'instructions' => 'Un lien par ligne',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 4,
				'formatting' => 'none',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-ville.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_page-periscoper',
		'title' => 'Page Periscoper',
		'fields' => array (
			array (
				'key' => 'field_57409a3bcea70',
				'label' => 'Nom',
				'name' => 'periscoper_name',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57409a48cea71',
				'label' => 'Nom d\'utilisateur',
				'name' => 'periscoper_username',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57409f76ef236',
				'label' => 'Ville',
				'name' => 'periscoper_city',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57409a54cea72',
				'label' => 'Image de profil',
				'name' => 'periscoper_profile_image',
				'type' => 'image',
				'required' => 1,
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_57409a6dcea73',
				'label' => 'Interview de La Gazette',
				'name' => 'periscoper_interview_url',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'page-periscoper.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
