#!/bin/sh

set -e

echo "Setting up your environment..."

#
# Check for Docker
#
if test ! $(which docker)
then
  echo -n " x You need to install Docker:"
  echo "  http://docs.docker.com/"
  exit
fi


#
# Check for docker-compose
#
if test ! $(which docker-compose)
then
  echo -n " x You need to install Docker Compose:"
  echo "  http://docs.docker.com/compose/install/"
  exit
fi

echo "Copying config"
cp wp-config.php.dist wp-config.php

echo "Starting"
docker-compose up -d

echo "Loading dump. It can take some times...."
docker-compose run --rm mysql mysql -hmysql -uroot -pleurfairepeur nuitdebout < dump/nuitdebout_multisite.sql

IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker-compose ps -q web))
echo "All done. Add to your /etc/hosts: $IP nuitdebout.dev"
