---
- name: Install PHP packages
  sudo: yes
  apt:  package={{ item.package }} state=latest
  with_items: php_packages

- name: Enable PHP packages
  sudo: yes
  command: /usr/sbin/php5enmod {{ item.name }} creates=/etc/php5/cli/conf.d/20-{{ item.name }}.ini
  with_items: php_packages
  notify: restart php5-fpm
